"""last_modified/created columns

Revision ID: 5dacfc86c316
Revises: dc15b0e992a4
Create Date: 2019-05-27 19:34:47.807199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dacfc86c316'
down_revision = 'dc15b0e992a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_items', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('co_items', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_co_items_created'), 'co_items', ['created'], unique=False)
    op.create_index(op.f('ix_co_items_last_modified'), 'co_items', ['last_modified'], unique=False)
    op.add_column('food_items', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('food_items', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_food_items_created'), 'food_items', ['created'], unique=False)
    op.create_index(op.f('ix_food_items_last_modified'), 'food_items', ['last_modified'], unique=False)
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_created'), 'users', ['created'], unique=False)
    op.create_index(op.f('ix_users_last_modified'), 'users', ['last_modified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_modified'), table_name='users')
    op.drop_index(op.f('ix_users_created'), table_name='users')
    op.drop_column('users', 'last_modified')
    op.drop_column('users', 'created')
    op.drop_index(op.f('ix_food_items_last_modified'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_created'), table_name='food_items')
    op.drop_column('food_items', 'last_modified')
    op.drop_column('food_items', 'created')
    op.drop_index(op.f('ix_co_items_last_modified'), table_name='co_items')
    op.drop_index(op.f('ix_co_items_created'), table_name='co_items')
    op.drop_column('co_items', 'last_modified')
    op.drop_column('co_items', 'created')
    # ### end Alembic commands ###
