"""shaak and daal tables

Revision ID: 8631405b994e
Revises: 9e4d35e5f23a
Create Date: 2019-05-24 14:24:56.085355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8631405b994e'
down_revision = '9e4d35e5f23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daal', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shaak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shaak', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shaak')
    op.drop_table('daal')
    # ### end Alembic commands ###
